import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as DocumentPicker from "expo-document-picker";
import { router } from "expo-router";
import React, { useMemo, useState } from "react";
import { Alert, FlatList, Modal, Pressable, ScrollView, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { BrandHeader, EmptyState, Field, Pill, PrimaryButton, SearchBox, SectionTitle, palette } from "@/components/gestionale-ui";
import { BusinessDocument, DocumentLine, useGestionale } from "@/lib/gestionale-context";
import { useColors } from "@/hooks/use-colors";

const types = ["Tutti", "Ordine", "Preventivo", "Proforma", "DDT", "Fattura", "Nota di Credito", "Fattura ricevuta"];
const newLine = (): DocumentLine => ({ id: String(Date.now() + Math.random()), descrizione: "", quantita: 1, prezzo: 0, sconto: 0, iva: 22 });
const blank = (): Omit<BusinessDocument, "id"> => ({ tipo: "Ordine", numero: "", cliente: "", data: new Date().toISOString().slice(0, 10), stato: "bozza", commento: "", righe: [newLine()], pagamento: "Bonifico bancario", causale: "Vendita", porto: "Franco" });
const total = (d: Pick<BusinessDocument, "righe">) => (d.righe || []).reduce((sum, r) => sum + r.quantita * r.prezzo * (1 - r.sconto / 100) * (1 + r.iva / 100), 0);

export default function DocumentsScreen() {
  const colors = useColors(); const { documents, clients, addDocument, updateDocument, removeDocument, attachPdfToDocument } = useGestionale();
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("Tutti"); const [open, setOpen] = useState(false);
  const [form, setForm] = useState<Omit<BusinessDocument, "id">>(blank()); const [editing, setEditing] = useState<BusinessDocument | null>(null);
  const filtered = useMemo(() => documents.filter((d) => (filter === "Tutti" || d.tipo === filter) && [d.tipo, d.numero, d.cliente, d.stato].join(" ").toLowerCase().includes(query.toLowerCase())), [documents, filter, query]);
  const edit = (d?: BusinessDocument) => { setEditing(d || null); setForm(d ? { ...d, righe: d.righe?.length ? d.righe : [newLine()] } : blank()); setOpen(true); };
  const save = async () => { if (!form.cliente.trim() || !(form.righe || []).some((r) => r.descrizione.trim())) return Alert.alert("Dati mancanti", "Inserisci cliente e almeno una riga."); const value = { ...form, numero: form.numero || String(documents.filter((d) => d.tipo === form.tipo).length + 1) }; if (editing) await updateDocument(editing.id, value); else await addDocument(value); setOpen(false); };
  const linked = (source: BusinessDocument, tipo: string) => { setEditing(null); setForm({ ...source, tipo, numero: "", data: new Date().toISOString().slice(0, 10), stato: "bozza", origineTipo: source.tipo, origineNumero: source.numero, riferimento: `${source.tipo} n. ${source.numero}`, righe: source.righe?.map((r) => ({ ...r, id: String(Date.now() + Math.random()) })) || [newLine()] }); setOpen(true); };
  return <ScreenContainer className="px-5 pt-5" edges={["top", "left", "right"]}>
    <BrandHeader title="Documenti" subtitle="Ordini, preventivi, DDT, fatture e note di credito" onMenu={() => router.push("/settings")} />
    <View style={{ flexDirection: "row", gap: 9, marginBottom: 12 }}><View style={{ flex: 1 }}><SearchBox value={query} onChangeText={setQuery} placeholder="Cerca documento o cliente..." /></View><Pressable onPress={() => edit()} style={{ width: 46, height: 46, borderRadius: 13, backgroundColor: palette.blue, alignItems: "center", justifyContent: "center" }}><MaterialIcons name="note-add" size={21} color="white" /></Pressable></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingBottom: 15 }}>{types.map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={{ borderRadius: 9, paddingHorizontal: 13, paddingVertical: 8, backgroundColor: filter === item ? palette.blue : "#EAF1F4" }}><Text style={{ color: filter === item ? "white" : palette.muted, fontSize: 12, fontWeight: "800" }}>{item}</Text></Pressable>)}</ScrollView>
    <SectionTitle title={`${filtered.length} documenti`} action="Nuovo" onPress={() => edit()} />
    <FlatList data={filtered} keyExtractor={(d) => String(d.id)} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<EmptyState icon="description" title="Nessun documento" description="Crea il primo documento commerciale." />} renderItem={({ item }) => <DocumentRow item={item} onEdit={() => edit(item)} onDelete={() => Alert.alert("Elimina documento", `Eliminare ${item.tipo} n. ${item.numero}?`, [{ text: "Annulla", style: "cancel" }, { text: "Elimina", style: "destructive", onPress: () => removeDocument(item.id) }])} onLinked={linked} onAttach={async () => { const result = await DocumentPicker.getDocumentAsync({ type: "application/pdf", copyToCacheDirectory: true }); if (!result.canceled) await attachPdfToDocument(item.id, { uri: result.assets[0].uri, name: result.assets[0].name }); }} />} />
    <Editor open={open} close={() => setOpen(false)} form={form} setForm={setForm} clients={clients.map((c) => c.denominazione)} save={save} editing={Boolean(editing)} colors={colors} />
  </ScreenContainer>;
}

function Editor({ open, close, form, setForm, clients, save, editing, colors }: { open: boolean; close: () => void; form: Omit<BusinessDocument, "id">; setForm: React.Dispatch<React.SetStateAction<Omit<BusinessDocument, "id">>>; clients: string[]; save: () => Promise<void>; editing: boolean; colors: ReturnType<typeof useColors> }) {
  const set = (key: keyof typeof form, value: any) => setForm((v) => ({ ...v, [key]: value })); const rows = form.righe || [];
  const changeRow = (i: number, key: keyof DocumentLine, value: string) => set("righe", rows.map((r, n) => n === i ? { ...r, [key]: key === "descrizione" ? value : Number(value.replace(",", ".")) || 0 } : r));
  return <Modal visible={open} animationType="slide" presentationStyle="pageSheet" onRequestClose={close}><ScreenContainer className="px-5 pt-5" edges={["top", "bottom", "left", "right"]}><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}><Text style={{ color: colors.foreground, fontSize: 22, fontWeight: "800" }}>{editing ? `Modifica ${form.tipo}` : "Nuovo documento"}</Text><Pressable onPress={close}><MaterialIcons name="close" size={25} color={colors.muted} /></Pressable></View><ScrollView contentContainerStyle={{ paddingBottom: 28 }}>
    <Text style={{ color: colors.muted, fontSize: 12, fontWeight: "700", marginBottom: 7 }}>Tipo documento</Text><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 14 }}>{types.slice(1).map((t) => <Pressable key={t} onPress={() => set("tipo", t)} style={{ paddingHorizontal: 11, paddingVertical: 8, borderRadius: 9, backgroundColor: form.tipo === t ? palette.blue : "#EAF1F4" }}><Text style={{ color: form.tipo === t ? "white" : palette.muted, fontSize: 12, fontWeight: "800" }}>{t}</Text></Pressable>)}</View>
    <Field label="Cliente / destinatario *" value={form.cliente} onChangeText={(v) => set("cliente", v)} placeholder={clients[0] || "Cliente"} /><Field label="Numero" value={String(form.numero)} onChangeText={(v) => set("numero", v)} keyboardType="numeric" /><Field label="Data" value={form.data} onChangeText={(v) => set("data", v)} placeholder="AAAA-MM-GG" /><Field label="Riferimento documento" value={form.riferimento || ""} onChangeText={(v) => set("riferimento", v)} />
    <Text style={{ color: colors.foreground, fontSize: 17, fontWeight: "800", marginTop: 10, marginBottom: 8 }}>Righe documento</Text>{rows.map((r, i) => <View key={r.id} style={{ borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 12, marginBottom: 10 }}><View style={{ flexDirection: "row", justifyContent: "space-between" }}><Text style={{ color: colors.muted, fontWeight: "800" }}>Riga {i + 1}</Text>{rows.length > 1 ? <Pressable onPress={() => set("righe", rows.filter((_, n) => n !== i))}><MaterialIcons name="delete-outline" size={20} color="#B42318" /></Pressable> : null}</View><Field label="Descrizione *" value={r.descrizione} onChangeText={(v) => changeRow(i, "descrizione", v)} /><View style={{ flexDirection: "row", gap: 8 }}><View style={{ flex: 1 }}><Field label="Q.tà" value={String(r.quantita)} onChangeText={(v) => changeRow(i, "quantita", v)} keyboardType="numeric" /></View><View style={{ flex: 1 }}><Field label="Prezzo €" value={String(r.prezzo)} onChangeText={(v) => changeRow(i, "prezzo", v)} keyboardType="numeric" /></View></View><View style={{ flexDirection: "row", gap: 8 }}><View style={{ flex: 1 }}><Field label="Sconto %" value={String(r.sconto)} onChangeText={(v) => changeRow(i, "sconto", v)} keyboardType="numeric" /></View><View style={{ flex: 1 }}><Field label="IVA %" value={String(r.iva)} onChangeText={(v) => changeRow(i, "iva", v)} keyboardType="numeric" /></View></View></View>)}
    <PrimaryButton label="Aggiungi riga" icon="add" variant="secondary" onPress={() => set("righe", [...rows, newLine()])} /><Text style={{ color: colors.foreground, fontSize: 18, fontWeight: "800", marginTop: 18 }}>Totale € {total(form).toFixed(2)}</Text>
    {form.tipo === "DDT" ? <><Field label="Causale trasporto" value={form.causale || ""} onChangeText={(v) => set("causale", v)} /><Field label="Vettore / corriere" value={form.vettore || ""} onChangeText={(v) => set("vettore", v)} /><Field label="Colli" value={form.colli || ""} onChangeText={(v) => set("colli", v)} /></> : <><Field label="Pagamento" value={form.pagamento || ""} onChangeText={(v) => set("pagamento", v)} /><Field label="Scadenza" value={form.scadenza || ""} onChangeText={(v) => set("scadenza", v)} placeholder="AAAA-MM-GG" /></>}<Field label="Note" value={form.commento || ""} onChangeText={(v) => set("commento", v)} multiline /><PrimaryButton label={editing ? "Salva modifiche" : "Crea documento"} icon="save" onPress={save} /></ScrollView></ScreenContainer></Modal>;
}

function DocumentRow({ item, onEdit, onDelete, onLinked, onAttach }: { item: BusinessDocument; onEdit: () => void; onDelete: () => void; onLinked: (d: BusinessDocument, type: string) => void; onAttach: () => Promise<void> }) { const colors = useColors(); return <Pressable onPress={onEdit} style={{ backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 15, padding: 14, marginBottom: 9 }}><View style={{ flexDirection: "row", alignItems: "center" }}><View style={{ width: 43, height: 43, borderRadius: 13, backgroundColor: item.tipo === "DDT" ? "#E9F6F1" : "#E8F2F8", alignItems: "center", justifyContent: "center", marginRight: 12 }}><MaterialIcons name={item.tipo === "DDT" ? "local-shipping" : "description"} size={21} color={palette.blue} /></View><View style={{ flex: 1 }}><Text style={{ color: colors.foreground, fontSize: 14, fontWeight: "800" }}>{item.tipo} n. {item.numero}</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 4 }}>{item.cliente} · {item.data}</Text><Text style={{ color: palette.blue, fontSize: 12, fontWeight: "800", marginTop: 5 }}>€ {total(item).toFixed(2)} · {item.attachment?.fileName || "Allega PDF"}</Text></View><Pill label={item.stato || "bozza"} tone="blue" /></View><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 12 }}><Mini label="Modifica" icon="edit" onPress={onEdit} /><Mini label="Allega" icon="attach-file" onPress={onAttach} /><Mini label="Crea da questo" icon="content-copy" onPress={() => Alert.alert("Crea documento", "Scegli il documento collegato", ["Ordine", "Preventivo", "Proforma", "DDT", "Fattura", "Nota di Credito"].map((t) => ({ text: t, onPress: () => onLinked(item, t) }))) } /><Mini label="Elimina" icon="delete-outline" danger onPress={onDelete} /></View></Pressable>; }
function Mini({ label, icon, onPress, danger }: { label: string; icon: any; onPress: () => void; danger?: boolean }) { return <Pressable onPress={onPress} style={{ flexDirection: "row", gap: 3, alignItems: "center", paddingVertical: 6, paddingHorizontal: 8, borderRadius: 8, backgroundColor: danger ? "#FFF1F0" : "#EAF1F4" }}><MaterialIcons name={icon} size={14} color={danger ? "#B42318" : palette.blue} /><Text style={{ color: danger ? "#B42318" : palette.blue, fontSize: 11, fontWeight: "800" }}>{label}</Text></Pressable>; }
