import AsyncStorage from "@react-native-async-storage/async-storage";
import * as FileSystem from "expo-file-system/legacy";
import React, { createContext, useContext, useEffect, useMemo, useState } from "react";
import { importedSeedData } from "@/data/seedData";
import { createTRPCClient } from "@/lib/trpc";
import { deleteWindowsDocument, isWindowsCloudConnected, loginWindowsCloud, pullWindowsDocuments, saveWindowsDocument } from "@/lib/windows-cloud";

export type Client = { id: number; codice?: string; denominazione: string; ragione_sociale?: string; partita_iva?: string; codice_fiscale?: string; indirizzo?: string; cap?: string; citta?: string; provincia?: string; telefono?: string; cellulare?: string; email?: string; pec?: string; referente?: string; note?: string; is_cliente?: number; is_fornitore?: number };
export type Company = { id: number; denominazione: string; sottotitolo?: string; indirizzo?: string; cap?: string; citta?: string; provincia?: string; partita_iva?: string; codice_fiscale?: string; telefono?: string; email?: string };
export type Attachment = { fileName: string; mimeType: "application/pdf" | "image/jpeg" | "image/png"; localUri?: string; remoteUrl?: string; storageKey?: string; uploadedAt?: number };
export type DocumentLine = { id: string; descrizione: string; quantita: number; prezzo: number; sconto: number; iva: number };
export type Destination = { nome: string; indirizzo?: string; cap?: string; citta?: string; provincia?: string };
export type BusinessDocument = {
  id: number; cloudId?: string; cloudCompanyId?: string; cloudClientId?: string; tipo: string; data: string; numero: number | string; cliente: string;
  stato?: string; commento?: string; attachment?: Attachment;
  clienteId?: number; destinatario?: Destination; destinazione?: Destination;
  righe?: DocumentLine[]; pagamento?: string; scadenza?: string;
  riferimento?: string; origineTipo?: string; origineNumero?: string | number;
  causale?: string; vettore?: string; colli?: string; porto?: string;
};
export type Movement = { id: number; data: string; descrizione: string; importo: number; direzione: "entrata" | "uscita"; categoria?: string; metodo?: string; conto?: string };

type Store = { clients: Client[]; companies: Company[]; documents: BusinessDocument[]; movements: Movement[]; hydrated: boolean; updatedAt: number };
type ContextValue = Store & { addClient: (client: Omit<Client, "id">) => Promise<void>; updateClient: (id: number, client: Partial<Client>) => Promise<void>; removeClient: (id: number) => Promise<void>; addDocument: (document: Omit<BusinessDocument, "id">) => Promise<void>; updateDocument: (id: number, document: Partial<BusinessDocument>) => Promise<void>; removeDocument: (id: number) => Promise<void>; addMovement: (movement: Omit<Movement, "id">) => Promise<void>; attachPdfToDocument: (id: number, file: { uri: string; name: string }) => Promise<void>; syncNow: () => Promise<{ status: "uploaded" | "downloaded" | "unchanged" | "error"; message?: string }>; connectWindowsCloud: (email: string, password: string) => Promise<void>; resetDemoData: () => Promise<void> };

const STORAGE_KEY = "gestione-aziendale-local-v2";
export const SYNC_WORKSPACE_KEY = "DOMINIK_MAGIC_03636480828";
const DEVICE_ID = "android-app";
const api = createTRPCClient();
const initialStore = (): Store => ({
  clients: importedSeedData.clients.map((c: any) => ({ ...c, denominazione: c.denominazione || c.ragione_sociale || "Senza denominazione" })),
  companies: importedSeedData.companies as readonly Company[] as Company[],
  documents: [...(importedSeedData.documents as readonly any[]), ...(importedSeedData.ddt as readonly any[]).map((d) => ({ id: Number(d.id) + 100000, tipo: "DDT", data: d.data_inizio_trasporto || new Date().toISOString().slice(0, 10), numero: d.num_doc || d.id, cliente: d.cliente || "Cliente non indicato", stato: "archiviato", commento: d.causale || "Documento di trasporto" })), ...(importedSeedData.invoices as readonly any[]).map((f) => ({ id: Number(f.id) + 200000, tipo: "Fattura", data: new Date().toISOString().slice(0, 10), numero: f.num_doc || f.id, cliente: f.cliente || "Cliente non indicato", stato: "da incassare", commento: f.descrizione || "" }))].map((d: any) => ({ ...d, numero: d.numero ?? d.id })),
  movements: [...(importedSeedData.movements as readonly any[]).map((m) => ({ ...m, importo: Number(m.importo || 0), direzione: m.direzione === "uscita" ? "uscita" : "entrata", descrizione: m.descrizione || "Movimento finanziario" })), ...(importedSeedData.receipts as readonly any[]).map((r) => ({ id: Number(r.id) + 300000, data: r.data || new Date().toISOString().slice(0, 10), descrizione: `Incasso ${r.tipo_documento || "documento"} · ${r.cliente || "Cliente"}`, importo: Number(r.importo || 0), direzione: "entrata" as const, categoria: "Incasso", metodo: r.metodo || "" })), ...(importedSeedData.payments as readonly any[]).map((p) => ({ id: Number(p.id) + 400000, data: p.data || new Date().toISOString().slice(0, 10), descrizione: `Pagamento · ${p.fornitore || "Fornitore"}`, importo: Number(p.importo || 0), direzione: "uscita" as const, categoria: "Pagamento", metodo: p.metodo || "" }))],
  hydrated: true, updatedAt: Date.now(),
});

const withoutRuntime = (store: Store) => ({ ...store, hydrated: true });
function parseStore(payload: string): Store | null { try { const parsed = JSON.parse(payload); if (!parsed || !Array.isArray(parsed.clients) || !Array.isArray(parsed.documents)) return null; return { ...parsed, hydrated: true }; } catch { return null; } }

const GestionaleContext = createContext<ContextValue | null>(null);
export function GestionaleProvider({ children }: { children: React.ReactNode }) {
  const [store, setStore] = useState<Store>({ ...initialStore(), hydrated: false });
  const [syncStatus, setSyncStatus] = useState<"idle" | "syncing" | "error">("idle");
  useEffect(() => { (async () => { const raw = await AsyncStorage.getItem(STORAGE_KEY); let local = raw ? parseStore(raw) : initialStore(); if (!local) local = initialStore(); setStore({ ...local, hydrated: true }); try { const remote = await api.sync.pull.query({ workspaceKey: SYNC_WORKSPACE_KEY }); if (remote?.payload && (!raw || remote.updatedAt > local.updatedAt)) { const remoteStore = parseStore(remote.payload); if (remoteStore) { setStore(remoteStore); await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(remoteStore)); } } } catch { /* offline: local data remains available */ } })(); }, []);

  const syncNow = async () => { setSyncStatus("syncing"); try { if (await isWindowsCloudConnected()) { const documents = await pullWindowsDocuments(); const next = { ...store, documents, updatedAt: Date.now(), hydrated: true }; setStore(next); await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(next)); setSyncStatus("idle"); return { status: "downloaded" as const }; } const remote = await api.sync.pull.query({ workspaceKey: SYNC_WORKSPACE_KEY }); if (remote?.payload && remote.updatedAt > store.updatedAt) { const remoteStore = parseStore(remote.payload); if (remoteStore) { setStore(remoteStore); await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(remoteStore)); setSyncStatus("idle"); return { status: "downloaded" as const }; } } const updatedAt = Math.max(Date.now(), store.updatedAt + 1); const next = { ...store, updatedAt, hydrated: true }; await api.sync.push.mutate({ workspaceKey: SYNC_WORKSPACE_KEY, deviceId: DEVICE_ID, payload: JSON.stringify(withoutRuntime(next)), updatedAt }); setStore(next); await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(next)); setSyncStatus("idle"); return { status: remote ? "uploaded" as const : "uploaded" as const }; } catch (error) { setSyncStatus("error"); return { status: "error" as const, message: error instanceof Error ? error.message : "Sincronizzazione non disponibile" }; } };
  const persist = async (next: Store) => { const withTime = { ...next, updatedAt: Math.max(Date.now(), store.updatedAt + 1), hydrated: true }; setStore(withTime); await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(withTime)); try { await api.sync.push.mutate({ workspaceKey: SYNC_WORKSPACE_KEY, deviceId: DEVICE_ID, payload: JSON.stringify(withoutRuntime(withTime)), updatedAt: withTime.updatedAt }); } catch { /* il dato resta sul telefono e verrà inviato dal pulsante Sincronizza */ } };
  const value = useMemo<ContextValue>(() => ({ ...store, addClient: async (client) => persist({ ...store, clients: [{ ...client, id: Date.now() }, ...store.clients] }), updateClient: async (id, client) => persist({ ...store, clients: store.clients.map((item) => item.id === id ? { ...item, ...client } : item) }), removeClient: async (id) => persist({ ...store, clients: store.clients.filter((item) => item.id !== id) }), addDocument: async (document) => { let saved: any = { ...document, id: Date.now() }; if (await isWindowsCloudConnected()) saved = await saveWindowsDocument(saved); await persist({ ...store, documents: [saved, ...store.documents] }); }, updateDocument: async (id, document) => { let saved: any = store.documents.find((item) => item.id === id); if (!saved) return; saved = { ...saved, ...document }; if (await isWindowsCloudConnected()) saved = await saveWindowsDocument(saved); await persist({ ...store, documents: store.documents.map((item) => item.id === id ? saved : item) }); }, removeDocument: async (id) => { const item = store.documents.find((doc) => doc.id === id); if (await isWindowsCloudConnected()) await deleteWindowsDocument(item?.cloudId); await persist({ ...store, documents: store.documents.filter((item) => item.id !== id) }); }, addMovement: async (movement) => persist({ ...store, movements: [{ ...movement, id: Date.now() }, ...store.movements] }), connectWindowsCloud: async (email, password) => { await loginWindowsCloud(email, password); }, attachPdfToDocument: async (id, file) => { const localUri = `${FileSystem.documentDirectory || ""}fattura-${id}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "_")}`; if (FileSystem.documentDirectory) await FileSystem.copyAsync({ from: file.uri, to: localUri }); let attachment: Attachment = { fileName: file.name, mimeType: "application/pdf", localUri, uploadedAt: Date.now() }; try { const base64 = await FileSystem.readAsStringAsync(localUri || file.uri, { encoding: "base64" as any }); const uploaded = await api.documents.uploadAttachment.mutate({ workspaceKey: SYNC_WORKSPACE_KEY, fileName: file.name, mimeType: "application/pdf", base64 }); attachment = { ...attachment, remoteUrl: uploaded.url, storageKey: uploaded.key }; } catch { /* conserva l allegato locale quando il dispositivo e offline */ } await persist({ ...store, documents: store.documents.map((doc) => doc.id === id ? { ...doc, attachment } : doc) }); }, syncNow, resetDemoData: async () => persist({ ...initialStore(), hydrated: true }) }), [store, syncStatus]);
  return <GestionaleContext.Provider value={value}>{children}</GestionaleContext.Provider>;
}
export function useGestionale() { const value = useContext(GestionaleContext); if (!value) throw new Error("useGestionale deve essere usato dentro GestionaleProvider"); return value; }



