import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { CameraView, useCameraPermissions } from "expo-camera";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";
import { router } from "expo-router";
import React, { useRef, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { PrimaryButton, palette } from "@/components/gestionale-ui";
import { useColors } from "@/hooks/use-colors";

export default function ScanScreen() {
  const colors = useColors();
  const [permission, requestPermission] = useCameraPermissions();
  const cameraRef = useRef<CameraView>(null);
  const [facing, setFacing] = useState<"back" | "front">("back");
  const [photoUri, setPhotoUri] = useState<string | null>(null);
  if (!permission) return <ScreenContainer><View /> </ScreenContainer>;
  if (!permission.granted) return <ScreenContainer className="px-5 pt-5" edges={["top", "bottom", "left", "right"]}><View style={styles.permission}><MaterialIcons name="document-scanner" size={52} color={palette.blue} /><Text style={{ color: colors.foreground, fontSize: 21, fontWeight: "800", textAlign: "center", marginTop: 18 }}>Scansiona un documento</Text><Text style={{ color: colors.muted, fontSize: 14, lineHeight: 21, textAlign: "center", marginTop: 8, marginBottom: 22 }}>Consenti l&apos;accesso alla fotocamera per acquisire fatture, DDT e ricevute.</Text><PrimaryButton label="Consenti fotocamera" icon="photo-camera" onPress={requestPermission} /><Pressable onPress={() => router.back()} style={{ padding: 16 }}><Text style={{ color: palette.blue, fontWeight: "700" }}>Annulla</Text></Pressable></View></ScreenContainer>;
  async function takePhoto() { const result = await cameraRef.current?.takePictureAsync({ quality: 0.85, exif: false }); if (!result?.uri) return; const name = `scansione-${new Date().toISOString().replace(/[:.]/g, "-")}.jpg`; const destination = `${FileSystem.documentDirectory || ""}${name}`; if (FileSystem.documentDirectory) await FileSystem.copyAsync({ from: result.uri, to: destination }); setPhotoUri(destination || result.uri); }
  async function sharePhoto() { if (!photoUri) return; if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(photoUri, { mimeType: "image/jpeg", dialogTitle: "Condividi scansione" }); else Alert.alert("Scansione salvata", "Il documento è stato salvato nella memoria dell'app."); }
  if (photoUri) return <ScreenContainer className="px-5 pt-5" edges={["top", "bottom", "left", "right"]}><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}><Text style={{ color: colors.foreground, fontSize: 22, fontWeight: "800" }}>Scansione acquisita</Text><Pressable onPress={() => router.back()}><MaterialIcons name="close" size={25} color={colors.muted} /></Pressable></View><View style={{ flex: 1, borderRadius: 18, backgroundColor: "#0A1720", alignItems: "center", justifyContent: "center", overflow: "hidden" }}><Text style={{ color: "#B9D2DE", fontSize: 14, textAlign: "center", padding: 25 }}>Foto salvata localmente nell&apos;app.{"\n"}Puoi condividerla o acquisire una nuova scansione.</Text></View><View style={{ gap: 10, paddingTop: 16 }}><PrimaryButton label="Condividi scansione" icon="share" onPress={sharePhoto} /><PrimaryButton label="Nuova scansione" icon="refresh" variant="secondary" onPress={() => setPhotoUri(null)} /></View></ScreenContainer>;
  return <View style={{ flex: 1, backgroundColor: "#08141D" }}><CameraView ref={cameraRef} style={{ flex: 1 }} facing={facing}><View style={styles.overlay}><View style={styles.topBar}><Pressable onPress={() => router.back()} style={styles.roundButton}><MaterialIcons name="close" size={23} color="white" /></Pressable><Text style={{ color: "white", fontSize: 17, fontWeight: "800" }}>Scansione documento</Text><Pressable onPress={() => setFacing((current) => current === "back" ? "front" : "back")} style={styles.roundButton}><MaterialIcons name="flip-camera-android" size={22} color="white" /></Pressable></View><View style={styles.frame}><View style={styles.cornerTL} /><View style={styles.cornerTR} /><View style={styles.cornerBL} /><View style={styles.cornerBR} /></View><View style={styles.bottomBar}><Text style={{ color: "#D8E8EF", fontSize: 12, textAlign: "center", marginBottom: 18 }}>Centra il documento nel riquadro e acquisisci la foto</Text><Pressable onPress={takePhoto} style={({ pressed }) => [styles.capture, pressed && { transform: [{ scale: 0.9 }], opacity: 0.8 }]}><View style={styles.captureInner} /></Pressable></View></View></CameraView></View>;
}
const styles = StyleSheet.create({ permission: { flex: 1, alignItems: "center", justifyContent: "center", padding: 25 }, overlay: { flex: 1, justifyContent: "space-between", padding: 20, backgroundColor: "#00000022" }, topBar: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingTop: 22 }, roundButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#00000088", alignItems: "center", justifyContent: "center" }, frame: { width: "84%", aspectRatio: 0.7, alignSelf: "center", position: "relative" }, cornerTL: { position: "absolute", left: 0, top: 0, width: 34, height: 34, borderLeftWidth: 3, borderTopWidth: 3, borderColor: "#FFFFFF" }, cornerTR: { position: "absolute", right: 0, top: 0, width: 34, height: 34, borderRightWidth: 3, borderTopWidth: 3, borderColor: "#FFFFFF" }, cornerBL: { position: "absolute", left: 0, bottom: 0, width: 34, height: 34, borderLeftWidth: 3, borderBottomWidth: 3, borderColor: "#FFFFFF" }, cornerBR: { position: "absolute", right: 0, bottom: 0, width: 34, height: 34, borderRightWidth: 3, borderBottomWidth: 3, borderColor: "#FFFFFF" }, bottomBar: { alignItems: "center", paddingBottom: 20 }, capture: { width: 76, height: 76, borderRadius: 38, borderWidth: 5, borderColor: "white", alignItems: "center", justifyContent: "center" }, captureInner: { width: 60, height: 60, borderRadius: 30, backgroundColor: "white" } });
